import { requestDto } from '@core/api/apiClient';
import { ChatHistoryDto, ChatMessageResponseDto } from './serverChat.dto';

/**
 * Server-backed chat, alongside the mock transport rather than replacing it.
 *
 * `chatSourceMode.ts` chooses and the default stays `mock`, so unit tests,
 * Storybook, and a backend-free dev session behave exactly as before.
 *
 * The chat store's bounded retention (300), pending cap (500), processed-id LRU
 * (2000), timestamp ordering, and flush batching are all upstream of this file
 * and untouched — this only produces messages for them to consume.
 */

export type ServerChatMessage = {
  id: string;
  clientMessageId: string;
  broadcastId: string;
  sequence: number;
  authorId: string;
  displayName: string;
  body: string;
  sentAt: string;
  deleted: boolean;
};

export type ChatStreamEvent =
  | { kind: 'message'; message: ServerChatMessage }
  | { kind: 'deleted'; messageId: string; sequence: number };

export type ChatConnectionState = 'connecting' | 'connected' | 'disconnected' | 'error';

/** One page of history. `nextCursor` is null once the page reached the end. */
export async function fetchChatHistory(
  broadcastId: string,
  afterSequence = 0,
  limit = 50,
): Promise<{ messages: ServerChatMessage[]; nextCursor: number | null; latestSequence: number }> {
  const response = await requestDto(
    {
      method: 'GET',
      url: `/live/broadcasts/${broadcastId}/chat/messages`,
      params: { afterSequence, limit },
    },
    ChatHistoryDto,
  );

  return {
    messages: response.messages as unknown as ServerChatMessage[],
    nextCursor: response.nextCursor,
    latestSequence: response.latestSequence,
  };
}

/**
 * Sends a message.
 *
 * The client id is generated by the caller and reused across retries — that is
 * what makes a retry after a timeout idempotent rather than posting twice. The
 * server returns the stored message either way, so an optimistic UI can reconcile
 * on it without needing to know whether it was the first attempt.
 */
export async function sendChatMessage(
  broadcastId: string,
  clientMessageId: string,
  body: string,
): Promise<ServerChatMessage> {
  const response = await requestDto(
    {
      method: 'POST',
      url: `/live/broadcasts/${broadcastId}/chat/messages`,
      data: { clientMessageId, body },
    },
    ChatMessageResponseDto,
  );

  return response;
}

export type ServerChatTransportOptions = {
  getAccessToken: () => string | null;
  /** The highest sequence already applied, so a rejoin catches up rather than refetching. */
  getLastSequence: () => number;
  baseUrl?: string;
  createSocket?: (url: string) => WebSocket;
};

/**
 * Read-only, deliberately: sending goes over HTTP where the idempotency key, the
 * rate limit, and the mute check already live. Duplicating that path over the
 * socket would mean two implementations of "may this person post?" that have to
 * agree forever.
 *
 * It does not reconnect. The chat controller already owns backoff with jitter.
 */
export class ServerChatTransport {
  private socket: WebSocket | null = null;
  private state: ChatConnectionState = 'disconnected';
  private readonly eventListeners = new Set<(event: ChatStreamEvent) => void>();
  private readonly stateListeners = new Set<(state: ChatConnectionState) => void>();

  constructor(private readonly options: ServerChatTransportOptions) {}

  connect(broadcastId: string): Promise<void> {
    this.disconnect();
    this.setState('connecting');

    return new Promise((resolve, reject) => {
      const socket = (this.options.createSocket ?? ((url: string) => new WebSocket(url)))(this.socketUrl());
      this.socket = socket;

      socket.addEventListener('open', () => {
        this.setState('connected');
        this.send({ event: 'join', data: { broadcastId, afterSequence: this.options.getLastSequence() } });
        resolve();
      });

      socket.addEventListener('message', (message: MessageEvent<unknown>) => {
        this.handleMessage(message.data);
      });

      socket.addEventListener('close', () => {
        this.setState('disconnected');
      });

      socket.addEventListener('error', () => {
        this.setState('error');
        reject(new Error('Chat transport connection failed'));
      });
    });
  }

  disconnect(): void {
    this.socket?.close();
    this.socket = null;
    this.setState('disconnected');
  }

  subscribe(listener: (event: ChatStreamEvent) => void): () => void {
    this.eventListeners.add(listener);
    return () => this.eventListeners.delete(listener);
  }

  subscribeConnection(listener: (state: ChatConnectionState) => void): () => void {
    this.stateListeners.add(listener);
    return () => this.stateListeners.delete(listener);
  }

  getConnectionState(): ChatConnectionState {
    return this.state;
  }

  private handleMessage(data: unknown): void {
    if (typeof data !== 'string') return;

    let parsed: unknown;
    try {
      parsed = JSON.parse(data);
    } catch {
      // One malformed frame is not a reason to tear down a working stream.
      return;
    }

    if (typeof parsed !== 'object' || parsed === null) return;

    const message = parsed as { type?: string; message?: ServerChatMessage; messageId?: string; sequence?: number };

    if (message.type === 'message' && message.message) {
      // Bound before the loop so the narrowing survives into the closure.
      const received = message.message;
      this.eventListeners.forEach((listener) => listener({ kind: 'message', message: received }));
      return;
    }

    /**
     * A tombstone rather than a silent removal: clients that already received the
     * message need to be told to drop it, and that is what makes them converge
     * without refetching history.
     */
    if (message.type === 'deleted' && message.messageId !== undefined) {
      const tombstone = { kind: 'deleted' as const, messageId: message.messageId, sequence: message.sequence ?? 0 };
      this.eventListeners.forEach((listener) => listener(tombstone));
      return;
    }

    if (message.type === 'error') this.setState('error');
  }

  private socketUrl(): string {
    const base = this.options.baseUrl ?? defaultBaseUrl();
    const token = this.options.getAccessToken();

    return token ? `${base}?token=${encodeURIComponent(token)}` : base;
  }

  private send(message: { event: string; data: unknown }): void {
    try {
      this.socket?.send(JSON.stringify(message));
    } catch {
      this.setState('error');
    }
  }

  private setState(state: ChatConnectionState): void {
    if (state === this.state) return;
    this.state = state;
    this.stateListeners.forEach((listener) => listener(state));
  }
}

function defaultBaseUrl(): string {
  const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  return `${protocol}//${window.location.host}/api/live/chat`;
}
